### ISSUE TITLE
Project rework

### ISSUE THREAD

**Issue by DevilIris** [DevilIris/Hearts-of-Iron-IV-The-Great-War#10]
Hello @MasterWaifuman  this is the new map. we need to export all the events, etc. basically the entire mod. 
Before to download read this 

# Delete the folder history/states only this one in tgw 
# delete the folder map/strategic regions in the tgw 
# delete the folder map/supply area in the tgw
with this you can start to fix the mod with the new map the link is here 
https://drive.google.com/file/d/1bzdxL1RIxPeh8xvj9f1uiNj3ZjERVShl/view
I hope that you like the new states 

# Also this instructions are clearly only delete that. delete no move or etc.  You need to DELETE the folders so the new version can work

**Comment by MasterWaifuman** [comment]
I will start this tomorrow, but this is a lot of work, so I'm not sure I can do it even in this month.

**Comment by DevilIris** [comment]
Ok so i update the repo here on Github and now is working. Well we have a lot of work 
We can divide the work in continents You can have Europe, Africa, and Russia(i know that is not a continent but russia is considered european)
I will work all the Americas, Oceania and Asia(In asia @skullbe  will help me with the chinese, japanese, and korean parts)

**Comment by MasterWaifuman** [comment]
ok

**Comment by DevilIris** [comment]
Also i see that in other branch you update the german colonies you can merge it with the new part so we can start working with all the nations

**Comment by MasterWaifuman** [comment]
I didn't complete all german colonies. I need to make 2 more. Then we can start working on other nation
