### ISSUE TITLE
Goals#2

### ISSUE THREAD

**Issue by DevilIris** [DevilIris/Hearts-of-Iron-IV-The-Great-War#11]
@MasterWaifuman  we have to complete basically all mod but with that said we can fix a lot of stuff and add more in the progress. You can expand the focus tree, events, etc. for Historical and non Historical.
Example a event that is important and the mod doesn't have if avoid the civil war as russia but with massive penalties, as well a event to choose if you kill the romanov family or no.
Add the France Wadai War 1909-1911, etc. 

And together we are going to fix the middle East that is the easy one. when i am done with america, i will start helping you in europe until @skullbe get online and help me with Asia.

--------------------------------
Things to do 
Europe: Rework everything put a strong germany and austro hungary. (MasterWaifuman(already doing))
Fix and check all the focuses of the european countries (MasterWaifuman)
Add a event to Romania to join the war (MasterWaifuman)
Fix the event to Bulgaria dont join the central powers and fix their focus (MasterWaifuman)
add more resources(i am going to put the resources in all map so the game can be balanced)(DevilIris)
fix the states manpower etc(i am going to make that too).(DevilIris)
check all the events peace script most likely the Italo Turkish war and the balkan wars (MasterWaifuman(already doing))
-------------
Asia Rework and the Xinhai The revolution and the NF trees of Japna, China and Kore.
Add more events like the Sakura-Thaft event  
 add more resources etc. 
-------------------
America 
Rework the entire continent and add the NF for Brazil, Mexico, Argentina, America and canada.
fix the states and the events of Bolivia mexico and the US

**Comment by MasterWaifuman** [comment]
> put a strong germany and austro hungary

Basically, Austria-Hungary was very weak. Even Russians could break their lines. Their generals were terrible and German Army by themselves defended Austria-Hungary. So Germany must be much much stronger.

**Comment by MasterWaifuman** [comment]
And make France waker as their combat doctrine was too old and outdated, so germany easily defeated them until some stupid german actions stopped their advancing.

**Comment by MasterWaifuman** [comment]
And germans underestimated bad infrastructure of france and belgium.

**Comment by DevilIris** [comment]
Yea qw dont want to make so op the cwntral powers cuz the multiplayer games

**Comment by DevilIris** [comment]
due to i remove the the new states until we finish the conversion we are going to work like this
