### ISSUE TITLE
Goals

### ISSUE THREAD

**Issue by DevilIris** [DevilIris/Hearts-of-Iron-IV-The-Great-War#3]
these are the goals for us right now 
1.- Fix the focus tree and events for russia 
2.- Fix the Xinhai Revolution as well make a focus tree for china (my focus tree for china doesnt work anymore )

3.-Make a focus Tree for Belgium, Spain
4.- Merge the subs mod of the curse of Huitzilopotchli. Brazil Focus Sub mod as well add the normal focus tree for Japan (Vanilla as a postwar tree like germany or Italy)
5.-Add more resources on the regions (no buff to special zones) I am going to do that (Done)
6.-Make the Korean Focus tree 
7.-Create the OOB´S for estonia and lituania (DONE)
8.-Improve the IA (I am going to do that stuff ) so the IA will not do a suicide navy invasion
9.-Improve South America as well with Europe(Done)
10.-Fix the Impassable Areas in Africa
11.-The neutral ideology now can send volunteers (DONE)
12. Fix the Mexican Focus tree. (DONE)
13.- Fix the localisation of the Russian focus tree on English Language 
14.- Add more generals to Austria Hungary & Italy
 15.- Fix borders errors in the region. Example a common error is Bolivia dont have chaco borreal (Done)
16.- Put a buff to the Central Power by National Spirits or Focuses because they are too weak (so weak than they surrender in 1916) DONE
17.-Adding more states(I am going to talk with citofis so he can make more of this as well reskin the units)
18.- Finally Test this parts and merge it with Wolferos Repo. 
19.- Release it :D 

(If you have more things to add type it on the comments)

**Comment by MasterWaifuman** [comment]
16.- Put a buff to the Central Power by National Spirits or Focuses because they are too weak (so weak than they surrender in 1916)

I think after Belgium capitulation I can add idea that increase organisation and recovery rate

**Comment by DevilIris** [comment]
The problem is that germany cant effort a invasion of belgium because they
get stock in the front they a need a push to invade belgium like
breaktrough bonus something like that

DevilIris

On Aug 13, 2017 4:02 AM, "Master Waifuman" <notifications@github.com> wrote:

16.- Put a buff to the Central Power by National Spirits or Focuses because
they are too weak (so weak than they surrender in 1916)

I think after Belgium capitulation I can add idea that increase
organisation and recovery rate

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/DevilIris/Hearts-of-Iron-IV-The-Great-War/issues/3#issuecomment-322030471>,
or mute the thread

**Comment by MasterWaifuman** [comment]
So may be some kind of debuff for entente at the start of war

**Comment by DevilIris** [comment]
That could be for russia in the ww1 the russian empire was the most of the
time loses against the germans but with france the stay in front of paris.
In game Germany never break nancy or liege. It could be a debuff Entente
and a buff cor CP only for 723 days.

DevilIris

On Aug 13, 2017 4:17 AM, "Master Waifuman" <notifications@github.com> wrote:

So may be some kind of debuff for entente at the start of war

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/DevilIris/Hearts-of-Iron-IV-The-Great-War/issues/3#issuecomment-322031051>,
or mute the thread

**Comment by MasterWaifuman** [comment]
I think debuff could be only for russia and belgium.

**Comment by DevilIris** [comment]
Yes i will make gfx of the NS. BTW i test a game 1910- 1932 there are 2
bugs with Sov
1.- they start with 0 troops the oob dont load almost they lose the war
2.- the event to choose wich countries is not only for Sov is for all the
players. When the event bew pops up. Is not like the xinhai or mexican
event because all the players can change the tag of Russia. In the other
hand all things that i test are fine but in my game as korea the Central
Powers. Surrender in 1916. But IA define works well they spawn a max 261
units for the people with slow Pcs.

DevilIris

**Comment by MasterWaifuman** [comment]
1.- they start with 0 troops the oob dont load almost they lose the war

I think I just fixed it. i will test it later.

2.- the event to choose wich countries is not only for Sov is for all the
players. When the event bew pops up. Is not like the xinhai or mexican
event because all the players can change the tag of Russia.

Yes, my fault. Forgot that it is major news event. I will add option trigger for RUS and not RUS.

**Comment by MasterWaifuman** [comment]
Thaaat strange. I looked through Nicholas Abdicates event and load_oob command should work. Game sees it but doesn't load.

**Comment by MasterWaifuman** [comment]
File itself is normal too. It is not even created by me

**Comment by MasterWaifuman** [comment]
1.- they start with 0 troops the oob dont load almost they lose the war

I didn't find a way to fix it. But i found another way to load oob

**Comment by MasterWaifuman** [comment]
So i made debuff NS and waiting for your gfx for it

**Comment by MasterWaifuman** [comment]
I created OOBs for EST and LIT

**Comment by MasterWaifuman** [comment]
11.-The neutral ideology now can send volunteers

This means we need to change send volunteers tension limit for neutral?

**Comment by DevilIris** [comment]
Yes the last one now the neutral idelogy can send volunters like the facist

DevilIris

**Comment by DevilIris** [comment]
I make the buff for both austria Hungary and Germany now

**Comment by DevilIris** [comment]
@121eddie  This are our goals. Also we didn´t merge your mod. Because i was waiting for your authorization. Can you merge your mod?

**Comment by 121eddie** [comment]
Well github doesn't allow to push if you are on a smartphone. So I will do it tomorrow 
Best Regards
Eduard lundi, 14 août 2017, 08:35AM +02:00 de Carlos  notifications@github.com :
